{{ if .Values.dydns.enabled -}}
{{ if .Values.dydns.secretEnv -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "factorio.fullname" . }}-dydns
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.dydns.secretEnv }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
{{- end }}
{{- end }}