{{- if .Values.factorio.persistence.create.enabled }}
{{ required "value for factorio.persistence.create.storageClass is required" .Values.factorio.persistence.create.storageClass }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "factorio.pvcName" . }}
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.factorio.persistence.create.size }}

  {{- if .Values.factorio.persistence.create.storageClass }}
  storageClassName: {{ .Values.factorio.persistence.create.storageClass }}
  {{- end }}
{{- end }}
